I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 31, in script
    p "Welcome to my little game"
Exception: Sayer 'p' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 31, in script
    p "Welcome to my little game"
  File "D:\Renpy\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\Renpy\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'p' is not defined.

Windows-10-10.0.19043 AMD64
Ren'Py 8.0.3.22090809
Two Truths And A Lie 1.0
Sun Oct 16 23:29:26 2022
